## GENERATED by tools/theme_backdrop_bake.gd - do not edit by hand.
##
## The palette each baked card backdrop in this folder was rendered from:
## the MD5 of data/themes/<id>.tres at bake time. A bake is a PHOTOGRAPH of
## a theme, so an edited palette leaves it showing colours the theme no
## longer has, and nothing about that fails at runtime - the card simply
## looks finished and is out of date. test_theme_backdrops.gd compares
## these stamps against the live .tres files and names what to re-bake.
##
## A script rather than a data file on purpose: the Android preset exports
## "all_resources", which carries scripts and imported textures and
## drops loose .json - and a manifest that vanishes on device turns the
## on-device half of that suite into a silent skip.
const FINGERPRINTS := {
	"altitude": "2bf91ad9460192455e0bc6fe1bcf2d25",
	"anime": "a834fab76a1eb1c686a11e5fb6f55b21",
	"antigrav": "78f23befa5881c9235e4206731159810",
	"aquarelle": "0ed6bc27f95b399a371e8dd79d430e94",
	"arcade": "9f5b7e1b37cd43cf6def5726c911bd31",
	"arctic": "a20023d7de0c265e4f7ed0e105ee56a9",
	"aurora": "c97ede4791474bff0e011b346cb6a74e",
	"autumn": "339dbc3dc573bd292944f9f741d666ba",
	"bioluminescence": "f27eb6d3bcfeb667596594b0da6c911a",
	"bismuth": "701607d0f4043930c3badd941776d665",
	"blood_moon": "ab652f240ac63286d6b7ae5421dc78b4",
	"butterfly_grove": "94759a1e170bc92dcd4d41a186a7a0da",
	"candy_pop": "2fd10607fd8c2840b095aade1b29666f",
	"carnival": "ef847e27baa48347f53e8f0dd14e86ac",
	"carrara": "e3aa8f9dc1d4ca933474535917941871",
	"circuit_pulse": "b72e4221d0337f50f5b1724e0553c8a1",
	"clockwork": "231c52d82a2de5d0563d01a39ffed643",
	"coral_depths": "8cb65133d72d91abe76992aff6059b6b",
	"cosmic_nebula": "50efb7c0a902a90e4122c3ff3a2ae1f0",
	"crystal_storm": "83377dd47148a0104129fca5cb63b3ee",
	"daybreak": "e034d93b288304ccae583c8c87a9e1c3",
	"desert_midnight": "83928ccd0ae823a0478c1ad4213b11da",
	"ember_serpent": "5542277ba92789573168cbf28f6e87c7",
	"emerald": "abb0c879828311ed58581e142a917e4f",
	"event_horizon": "6c2f04f847a7517e54766552a7ad41ce",
	"firefly_night": "302fe96c09709b94aad7c552a9f8eb26",
	"first_bloom": "5a711724d29841b92c63ed115cf8d87e",
	"honeycomb": "8b7bad2dd61f0d2d74cd82eb0778b560",
	"ink_wash": "be09ae44c9a4c9ce83ad78cd1bded35c",
	"kawaii": "91fe05a248a40e842006a84c02e8ac99",
	"koi_garden": "ef4c149c1df6c82cb8343cda41274a5c",
	"lagoon": "c7b4451003c84e2ca0d72f87fae41960",
	"lantern_festival": "f36300a1ba8e9b8d9011d820dbe4daff",
	"mono": "3ce4aed5f5f7d78b5abd922aaffc50b4",
	"moonlit_bamboo": "46d32397c171b0189fe6809c66507fc0",
	"neon_blue": "56b455ec4d719fa61d51be771af53912",
	"noir": "5c45be9d210e596980960319a3feefde",
	"nova_forge": "61ba47354ae39a2cf9f0855d25b2a278",
	"obsidian": "9b969b316ad88aa5ca4a0e0cb9e418c1",
	"ocean": "54bc63ad16fed9c2ec963db39ff43b26",
	"origami_sky": "4cb15f3b480cab8ac452d90ed6b1f7ed",
	"paper": "610cdd2d41e85e1dfd9b20121a9171e9",
	"peacock": "cd9d02f31bdc846a800eb162dc07d34e",
	"phantom_realm": "cdd1baadb34a134c563b2b715a2a126e",
	"raining_diamond": "d7bd7951fd1d3eeb6a2b18bb455c076d",
	"raining_gold": "5e002cc219f649162a16f2e738ef0a46",
	"raining_silver": "72353f0551caefe5ae8019b45fa08481",
	"redwood": "9a13d0974635a66c4cf100f5402d3cc9",
	"ronin": "c95a1bf98ef50b5dc9a49d54f15d7095",
	"ruby": "8c999e6005fbda49b1e622430025f68c",
	"sakura_pink": "f4797591ef254b4deca9ed678963d246",
	"sanctum": "fb68cfc74305b6d894eaf5e3264a3c47",
	"savanna": "16bba43967f8f642bf401fe2d27069e4",
	"shadow_fog": "24d1271ae8819481b8f0ded62495f4e6",
	"skywriter": "0e7e2ed65755033135bf8ecdd09a800f",
	"space": "84e3480f4812fb71f7ff14ca9c48c6f7",
	"star_atlas": "8b4df4d890903953e76ce9bed8d02477",
	"starforged": "6e61183429fc3eebf7cd8afd47b9b935",
	"thunderstorm": "0477069485128862a4cc559c04487e11",
	"vaporwave": "1b11ee9bfdfa22c775e464ccebe17ad4",
	"zen_garden": "c23857f30359128f2bbb4c89e5785084",
}
