class_name PlayGamesIds
extends RefCounted
## PlayGamesIds — the Play Games Services ID catalog.
##
## ⚠️ THE IDs BELOW ARE GENERATED BY PLAY CONSOLE AND ARE TIED TO ONE PLAY ACCOUNT.
## Every achievement and leaderboard is created there and Play mints the ids, so
## this file is deliberately the ONLY place they appear. Migration = edit this
## file. (See docs/premium/README.md → "Real-Play-account migration checklist".)
##
## Ships EMPTY, so PlayGames stays dormant for these features until they are
## filled in. No node/plugin dependencies, so it is testable.

## Our local Achievements.DEFS id  →  the Play Console achievement id ("CgkI...").
## ONE SLOT PER DEFS ID, kept in DEFS order: a DEFS id with no slot here unlocks
## locally but is silently never mirrored. tests/test_play_games_ids.gd derives
## its expectation from the real DEFS — add the achievement there, add the slot
## here, same commit.
const ACHIEVEMENTS := {
	"first_solve": "",
	"classic_series": "",
	"sprint_series": "",
	"lock_series": "",
	"twist_series": "",
	"fog_series": "",
	"classic_master": "",
	"lock_master": "",
	"twist_master": "",
	"perfect_pace": "",
	"perfect_run": "",
	"streak_7": "",
	"streak_30": "",
}

## Our mode id  →  that mode's "Best Series" leaderboard id ("CgkI...").
## Per-mode boards: the modes score entirely different things (moves against
## par, boards cleared on a clock), so a single board would rank whoever plays
## the most forgiving mode. EVERY mode gets a
## board; keep this in step with GameModes._CONFIGS — the suite derives its
## expectation from the catalog itself, so a new mode with no board fails there.
const LEADERBOARD_BEST_SCORE_BY_MODE := {
	"classic": "",
	"sprint": "",
	"lock": "",
	"twist": "",
	"fog": "",
}

## Longest win streak, across every mode.
const LEADERBOARD_HIGHEST_TILE := ""

## True once the Play Console ids have been filled in (any achievement mapped).
static func is_configured() -> bool:
	for id: String in ACHIEVEMENTS.values():
		if not id.is_empty():
			return true
	return false

## The Play achievement id for one of our local achievement ids, or "" if unmapped.
static func achievement(local_id: String) -> String:
	return String(ACHIEVEMENTS.get(local_id, ""))

## The Best Series leaderboard id for a mode, or "" if unmapped.
static func best_score_leaderboard(mode_id: String) -> String:
	return String(LEADERBOARD_BEST_SCORE_BY_MODE.get(mode_id, ""))
